<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anil" failures="1" tests="1" name="LoginandError" time="20.705" errors="0" timestamp="19 May 2024 15:24:35 GMT">
  <testcase classname="Tests.LoginError" name="loginError" time="6.663">
    <failure type="java.lang.AssertionError" message="expected [There is an error in the email or password] but found [There an error in the email or password]">
      <![CDATA[java.lang.AssertionError: expected [There is an error in the email or password] but found [There an error in the email or password]
at Tests.LoginError.loginError(LoginError.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginError -->
</testsuite> <!-- LoginandError -->
